version: '3'

services:
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - 8080:80
    networks:
      - mynetwork
    depends_on:
      - activemq
      - scheduler-instance1
      - consumer-instance1
      - accounts-instance1
      - accounts-instance2
  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker:dev.latest
    ports:
      - 61616:61616
      - 8161:8161
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
    networks:
      - mynetwork
  scheduler-instance1:
    build: ./scheduler
    networks:
      - mynetwork
    depends_on:
      - activemq
    expose:
      - 8081:8081
    environment:
      REQUEST_URL_CONSUMER: http://172.17.0.1:8080/accounts/transactions
      MQ_BROKER_URL: tcp://172.17.0.1:61616
  consumer-instance1:
    build: ./consumer
    networks:
      - mynetwork
    depends_on:
      - activemq
    expose:
      - 8082:8082
    environment:
      REQUEST_URL_ACCOUNTS: http://172.17.0.1:8080/accounts/transactions
      MQ_BROKER_URL: tcp://172.17.0.1:61616
  accounts-instance1:
    build: ./accounts
    networks:
      - mynetwork
    depends_on:
      - activemq
    expose:
      - 8083:8083
  accounts-instance2:
    build: ./accounts
    networks:
      - mynetwork
    depends_on:
      - activemq
    expose:
      - 8083:8083

networks:
  mynetwork:
