version: '3'

services:
  consumer-instance1:
    build: ./consumer
    networks:
      - mynetwork
    expose:
      - 8081:8081
  accounts-instance1:
    build: ./accounts
    networks:
      - mynetwork
    expose:
      - 8082:8082
  accounts-instance2:
    build: ./accounts
    networks:
      - mynetwork
    expose:
      - 8082:8082
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - 8080:80
    networks:
      - mynetwork
#  activemq:
#    image: rmohr/activemq
#    ports:
#      - 61616:61616
#      - 8161:8161
#    environment:
#      ACTIVEMQ_OPTS_MEMORY: "-Xms64M -Xmx256M"
#    networks:
#      - mynetwork

networks:
  mynetwork:
