apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: false
  access: proxy
  editable: true

- name: Elasticsearch
  type: elasticsearch
  access: proxy
  url: http://172.17.0.1:9200
  jsonData:
    esVersion: 8.12.2
    timeField: "@timestamp"
    httpHeaderName1: 'Authorization'
  secureJsonData:
    httpHeaderValue1: 'Basic ZWxhc3RpYzpjaGFuZ2VfbWU='
  isDefault: true
  editable: true