receivers:
  otlp:
    protocols:
      grpc:
      http:

# Dummy receiver that's never used, because a pipeline is required to have one.
#  otlp/spanmetrics:
#    protocols:
#      grpc:
#        endpoint: "localhost:65535"

processors:
  batch:
#  spanmetrics:
#    metrics_exporter: prometheus

exporters:
#  prometheus:
#    endpoint: "otel_collector:8889"
  logging:
    loglevel: info
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  otlphttp/elastic:
    endpoint: "http://172.17.0.1:8200"
    headers:
      Authorization: "Basic ZWxhc3RpYzpjaGFuZ2VfbWU="
    tls:
      insecure: true

service:
  pipelines:
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
#    metrics/spanmetrics:
#      receivers: [ otlp/spanmetrics ]
#      exporters: [ prometheus ]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, otlphttp/elastic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]