receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "otel_collector:8889"
  logging:
    loglevel: info
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  kafka:
    brokers:
      - "kafka:9092"
    protocol_version: 2.0.0

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, kafka]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, kafka]