global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
#  - job_name: otel_collector
#    static_configs:
#    - targets: ['otel_collector:8889']

  - job_name: applications
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
    - targets: ['scheduler-instance1:8081',
                'consumer-instance1:8082',
                'accounts-instance1:8083',
                'accounts-instance2:8083',
                'accounts-instance3:8083',
                'accounts-instance4:8083',
                'processor-instance1:8084']

  - job_name: node_exporter
    static_configs:
      - targets: ['172.17.0.1:9100']

  - job_name: docker
    static_configs:
      - targets: [ "172.17.0.1:8095" ]
