{
 "title": "Consumer Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "BROKER", "label": "BROKER", "query": "JMS, KAFKA" },
   {
    "name": "FORMAT",
    "label": "FORMAT",
    "query": "JSON, PROTOBUF, PROTOSTUFF, KRYO, MSGPACK"
   },
   {
    "name": "SIZE",
    "label": "SIZE",
    "query": "1, 5, 10, 25, 100, 500, 1000, 10000, 100000, 1000000"
   }
  ]
 },
 "panels": [
  { "title": "GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LESS -> GREATER TIME | EXECUTION SIZE: ${SIZE}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BROKERS | EXECUTION SIZE: ${SIZE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "JMS",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *JMS* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "KAFKA",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *KAFKA* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BROKER: ${BROKER} | {ALL FORMATS} | EXECUTION SIZE: ${SIZE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "JSON",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *${BROKER}* AND url.original: *JSON* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PROTOBUF",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *${BROKER}* AND url.original: *PROTOBUF* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PROTOSTUFF",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *${BROKER}* AND url.original: *PROTOSTUFF* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "KRYO",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *${BROKER}* AND url.original: *KRYO* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MSGPACK",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "url.original: *${BROKER}* AND url.original: *MSGPACK* AND url.original: *loop-size=${SIZE}*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}