{
 "title": "Consumidor Métricas",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "BROKER", "label": "BROKER", "query": "JMS, KAFKA" },
   {
    "name": "FORMAT",
    "label": "FORMAT",
    "query": "JSON, PROTOBUF, PROTOSTUFF, KRYO, MSGPACK"
   },
   {
    "name": "SIZE",
    "label": "SIZE",
    "query": "1, 5, 10, 25, 100, 500, 1000, 10000, 100000, 1000000"
   }
  ]
 },
 "panels": [
  { "title": "PAINEL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MENOR TEMPO -> MAIOR TEMPO | QTD EXECUÇÕES: ${SIZE}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "/scheduler/send-data?loop-size=${SIZE}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BROKER: ${BROKER} | QTD EXECUÇÕES: ${SIZE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "${BROKER}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "repeat": "BROKER",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "/scheduler/send-data?loop-size=${SIZE}&message-broker-type=${BROKER}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMS - {FORMAT} | QTD EXECUÇÕES: ${SIZE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "${FORMAT}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "repeat": "FORMAT",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "\"/scheduler/send-data?loop-size=${SIZE}&message-broker-type=JMS&message-format-type=${FORMAT}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "KAFKA - {FORMAT} | QTD EXECUÇÕES: ${SIZE}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "${FORMAT}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.original",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transaction.duration.us", "id": "1", "type": "avg" }
     ],
     "query": "\"/scheduler/send-data?loop-size=${SIZE}&message-broker-type=KAFKA&message-format-type=${FORMAT}\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}